name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
      # - uses: JamesIves/github-pages-deploy-action@v4
        with:
          submodules: 'recursive'
          cmd: |
            install
            test
          # folder: public
